# Generated by Django 3.0.7 on 2020-07-01 15:13

from django.db import migrations
from data_files.genres import genres

def create_genres(apps, schema_editor):
    Genre = apps.get_model('albums', 'Genre')
    for genre_name in genres:
        Genre.objects.create(name=genre_name)

class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20200701_1500'),
    ]

    operations = [
        # create genre objects
        migrations.RunPython(create_genres),
    ]
