# Generated by Django 3.0.7 on 2020-07-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20200701_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='', max_length=75),
            preserve_default=False,
        ),
    ]
