# Generated by Django 3.0.7 on 2020-07-01 19:34

from django.db import migrations
from django.utils.text import slugify

class Migration(migrations.Migration):

    def create_slugs(apps, schema_editor):
        Genre = apps.get_model('albums', 'Genre')
        genres = Genre.objects.all()
        for genre in genres:
            genre.slug = slugify(genre.name)
            genre.save()


    dependencies = [
        ('albums', '0004_genre_slug'),
    ]

    operations = [
        migrations.RunPython(create_slugs),

    ]
